### ISSUE TITLE
Crate libc 0.2.154 is yanked

### ISSUE THREAD

**Issue by acgetchell** [rust-random/getrandom#456] opened 2024-06-05 18:13 UTC
This was flagged in actions-rust-lang/audit@v1.

**Comment by josephlr** [comment] 2024-06-05 19:08
Duplicate of #423

**Closed by josephlr** 2024-06-05 19:08 UTC

**Comment by josephlr** [comment] 2024-06-05 19:09
Note, a later version of libc has been released, so is there an issue here?

**Comment by acgetchell** [comment] 2024-06-05 20:20
uuid v1.8.0 use this crate, so presumably once they update this will be resolved.

**Comment by josephlr** [comment] 2024-06-05 20:29
@acgetchell you should be able to use the correct version of libc without and crates needing to do anything, as 0.2.155 is compatible with 0.2.154

**Comment by acgetchell** [comment] 2024-06-05 20:35
Ah, thanks. I'm not a direct consumer, though. Unless there's something I haven't understood from the Cargo book, I didn't see a way to specify libc 0.2.155 directly other than mucking around with Cargo.lock, which seems to be disfavored.

**Comment by josephlr** [comment] 2024-06-05 21:14
@acgetchell if the problematic `Cargo.lock` file is in your project you can either delete and regenerate it or call `cargo update` to bump your dependencies. This page explains how all that works: https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
