### ISSUE TITLE
Breaking change re: Error implementations on Windows

### ISSUE THREAD

**Issue by pie-flavor** [rust-random/getrandom#168] opened 2020-10-25 07:41 UTC
The re-addition of the default-implementations of std::error::Error without the std feature got all the relevant Linux platforms, but missed Windows, making it still a breaking change. I'm experiencing this issue downstream from bcrypt, which no longer compiles on Windows without overriding the getrandom dep.

**Comment by newpavlov** [comment] 2020-10-25 17:56
I think it should be fixed on the `bcrypt` side by forwarding the `std` feature. Plus simultaneously they also can update to `getrandom v0.2`, which does require such forwarding on Linux targets as well.

**Comment by josephlr** [comment] 2020-10-26 10:29
Look like this was resolved in https://github.com/Keats/rust-bcrypt/pull/57. However, we should still probably update the `0.1` branch to fix this. It was a breaking change, and adding the `std` stuff back for Windows shouldn't hurt anything.

**Comment by newpavlov** [comment] 2020-10-26 17:24
IIRC `std` stuff never worked on Windows in the first place, so it's not a breaking change, but an inconsistency between Linux and Windows targets.

**Comment by josephlr** [comment] 2020-10-26 22:26
> IIRC `std` stuff never worked on Windows in the first place, so it's not a breaking change, but an inconsistency between Linux and Windows targets.

You're right.

I confirmed that `v0.1.8` never had the `std::error::Error` implementations for Windows (unless you had the `"std"` feature enabled). So the removal and readding were not breaking changes on Windows. Closing as not a bug.

**Comment by pie-flavor** [comment] 2020-10-27 22:11
@josephlr 0.1.6 did, though.

**Comment by josephlr** [comment] 2020-10-27 22:29
> @josephlr 0.1.6 did, though. That just means the break took place slightly earlier.

Good catch, reopening.

**Closed** 2020-12-07 04:30 UTC
